# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

In [ ]:
import numpy as np

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
data1 = np.random.uniform(0, 20, 28).reshape(4, 7)
masiv_read1 = (data1 - np.min(data1)) / (np.max(data1) - np.min(data1))
print(masiv_read1)

[[1.         0.19079395 0.09702492 0.35494983 0.4993299  0.49824847
  0.49292407]
 [0.06974839 0.72690689 0.955821   0.06847904 0.76463558 0.06546705
  0.64665583]
 [0.         0.88177132 0.05599777 0.38785035 0.27975579 0.2629361
  0.24825218]
 [0.51972136 0.35197894 0.92459473 0.97236321 0.24747457 0.89917075
  0.48698983]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
matric = np.random.randint(0, 11, (8,10))
print(np.argsort(matric.sum(axis = 1))[0])

6


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
vectors = np.random.randint(0, 11, (2, 4))
print(np.linalg.norm(vectors[1] - vectors[0]))

6.48074069840786


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
print(np.around(np.linalg.inv(a) @ (c * (-1)) @ np.linalg.inv(b)))

[[ 1.  0.]
 [-2.  1.]
 [ 3. -4.]]


## Лабораторная работа №1

In [ ]:
import numpy as np

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
f = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32', skiprows = 1, delimiter = ',')
print(f[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
print(f'Среднее значение 2 столбца: {np.mean(f[:, 1])}, Cреднее значение 3 столбца {np.mean(f[:, 2])}')
print(f'Минимальное значение 2 столбца: {np.min(f[:, 1])}, Минимальное значение 3 столбца {np.min(f[:, 2])}')
print(f'Максимальное значение 2 столбца: {np.max(f[:, 1])}, Максимальное значение 3 столбца {np.max(f[:, 2])}')
print(f'Медиана 2 столбца: {np.median(f[:, 1])}, Медиана 3 столбца {np.median(f[:, 2])}')

Среднее значение 2 столбца: 21601.00169, Cреднее значение 3 столбца 9.05528
Минимальное значение 2 столбца: 0, Минимальное значение 3 столбца 1
Максимальное значение 2 столбца: 2147483647, Максимальное значение 3 столбца 39
Медиана 2 столбца: 40.0, Медиана 3 столбца 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
lim_by_quant = f.copy()
quant = np.quantile(lim_by_quant[:, 1], .75)
lim_by_quant[lim_by_quant[:, 1] > quant] = quant
print(lim_by_quant)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [    65     65     65]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
f1 = f.copy()
print(np.count_nonzero(f1[:,1] == 0))
f[f1[:,1] == 0] = 1
print(f)

479
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
f1 = f.copy()
print(np.unique(f1[:, 0]))

NameError: ignored

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
f1 = f.copy()
print(np.unique(f1[:, 2]))
print(np.unique(f1[:, 2]).size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
f1 = f.copy()
vers_1 = f1[f1[:, 2] <= 5] 
print(vers_1)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
f1 = f.copy()
masivik = f1[:, 2] / f1[:, 1]
print(masivik)
print(masivik.max())

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
f1 = f.copy()
kols = np.argsort(f[:, 1])[-100:]
print(np.mean(f[kols][:, 2]))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
f1 = f.copy()
print(f1[np.random.randint(0, f1.shape[0], 10)])

[[ 87678    190     12]
 [399346     40     11]
 [373198     60     18]
 [ 26835     70      9]
 [ 23765     22      8]
 [133993     60     17]
 [491187    270      9]
 [297873      5      3]
 [239533     80      6]
 [329425    125     11]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
f1 = f.copy()
sr = np.mean(f1[:, 2])
print((np.count_nonzero(f1[:, 2] < sr) * 100) / f.shape[0])

58.989


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
f1 = f.copy()
mask = (f1[:, 1] <= 20) & (f1[:, 2] <= 5).astype(int)
mask_data = np.concatenate((f1, mask.reshape(1, mask.size).T), axis = 1)
print(mask_data)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [ ]:
f1 = f.copy()
simple_set =  np.count_nonzero(mask_data[:, 3])
print((simple_set * 100) / f1.shape[0])

9.943


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
f1 = f.copy()
mask_smo = f1[f1[:, 1] < 10]
mask_nor = f1[(f1[:, 1] >= 10) & (f1[:, 1] < 20)]
mask_big = f1[f1[:, 1] >= 20]
max_kol = np.min([mask_smo.shape[0], mask_nor.shape[0], mask_big.shape[0]])
res_mas = np.array([mask_smo[:max_kol], mask_nor[:max_kol], mask_big[:max_kol]])
print(res_mas)





[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [     1      1      1]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]]
